# Generated by Django 5.0.6 on 2024-06-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='images/profile/default_profile.jpeg', upload_to='images/profile/'),
        ),
    ]
